### ISSUE TITLE
Reemplazar función de validación de cédulas

### ISSUE THREAD

**Issue by jonathanf** [Asuskf/diccionarioWPA2-PSK#1]
@Asuskf te recomiendo usar la librería stdnum para validar la cédula / ruc del ecuador.

`from stdnum.ec import ci, ruc`

`ci.is_valid('NÚMERO CI')  # Retorna un valor booleano que indica la validez de número de ci`
`ruc.is_valid('NÚMERO RUC')   # Retorna un valor booleano que indica la validez de número de ruc`

**Comment by Asuskf** [comment]
Saludos.
Gracias por tu aporte en el código, la verdad desconozco de muchas librerías que existe para python y bueno no fue tiempo mal invertido aplique la teoría en algo funcional.

Lo más pronto posible haré la mejora del código entre el viernes y sábado que es día para programa python.

Tengo planeado hacer un bot en python para el telegram python Quito me quiere ayudar con un feedback? :D

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
